/*
 * This source file was generated by the Gradle 'init' task
 */
package org.recieverman;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import org.recieverman.descriptors.World;
import org.recieverman.descriptors.entities.Event;
import org.recieverman.descriptors.entities.EventBus;
import org.recieverman.descriptors.entities.ParsedEvent;
import org.recieverman.descriptors.functional.Intension;
import org.recieverman.domains.Condition;
import org.recieverman.domains.DefaultEventParser;
import org.recieverman.domains.EventExpect;
import org.recieverman.domains.FieldAssertion;
import org.recieverman.domains.FulfillmentToken;
import org.recieverman.domains.FulfillmentReport;
import org.recieverman.domains.RoutedFulfillment;
import org.recieverman.domains.ScenarioRouter;
import org.recieverman.domains.ScenarioVerifier;
import org.recieverman.domains.StreamingScenarioVerifier;
import org.recieverman.domains.Supplier;
import org.recieverman.domains.SupplierScenario;
import org.recieverman.domains.SupplierTemplate;
import org.recieverman.domains.SupplierTemplateLoader;

public class ReceiverManTest {
    @Test public void testIntensionCalculus() throws Exception {
        ReceiverMan classUnderTest = new ReceiverMan();
        World world = new World(Clock.systemUTC());
        EventBus<Event> bus = new EventBus<>();
        // Intensional statement: "The server HL7s properly" + inchoative expectation.
        // "Expect an ADT^A01 that is not too delayed, within 2s."
        Intension<Event, Event> expectA01 =
            EventExpect.expectTypeFresh("ADT^A01", Duration.ofSeconds(5), Duration.ofSeconds(2));

        // Chain an inchoative: after A01, expect ORU^R01.
        Intension<Event, Event> scenario =
            EventExpect.afterSeeingThen(
                expectA01,
                a01 -> EventExpect.expectTypeFresh("ORU^R01", Duration.ofSeconds(5), Duration.ofSeconds(2))
            );

        CompletionStage<Event> done = scenario.run(world, bus);

        done.whenComplete((ev, ex) -> {
            if (ex != null) {
                System.out.println("[SCENARIO] FAILED: " + ex.getMessage());
            } else {
                System.out.println("[SCENARIO] COMPLETED by event: " + ev.raw());
            }
        });

        // Simulated emitter (asynchronous)
        Executors.newSingleThreadScheduledExecutor().schedule(() -> {
            System.out.println("[EMIT] ADT^A01 at " + Instant.now());
            bus.emit(new Event("ADT^A01|...", Instant.now()));
        }, 200, TimeUnit.MILLISECONDS);

        Executors.newSingleThreadScheduledExecutor().schedule(() -> {
            System.out.println("[EMIT] ORU^R01 at " + Instant.now());
            bus.emit(new Event("ORU^R01|...", Instant.now()));
        }, 500, TimeUnit.MILLISECONDS);

        Event result = done.toCompletableFuture().get();
        System.out.println("Scenario satisfied by: " + result.raw());
    }

    @Test public void verifiesSupplierScenarioFromEnteredEvents() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        Clock clock = Clock.fixed(now, ZoneOffset.UTC);
        Supplier supplier = new Supplier("Demo Supplier", List.of());
        SupplierScenario scenario = new SupplierScenario("Admission result flow", List.of(
            new Condition("Admission received", "ADT^A01", Duration.ofMinutes(10), Duration.ofSeconds(10)),
            new Condition("Result received", "ORU^R01", Duration.ofMinutes(10), Duration.ofSeconds(10))
        ));

        FulfillmentReport report = new ScenarioVerifier().verify(supplier, scenario, List.of(
            new Event("ADT^A01|one", now.minusSeconds(3)),
            new Event("ORU^R01|two", now.minusSeconds(1))
        ), clock);

        assertTrue(report.fulfilled());
        assertEquals(report.results().size(), 2);
    }

    @Test public void reportsMissingLaterCondition() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        Clock clock = Clock.fixed(now, ZoneOffset.UTC);
        Supplier supplier = new Supplier("Demo Supplier", List.of());
        SupplierScenario scenario = new SupplierScenario("Admission result flow", List.of(
            new Condition("Admission received", "ADT^A01", Duration.ofMinutes(10), Duration.ofSeconds(10)),
            new Condition("Result received", "ORU^R01", Duration.ofMinutes(10), Duration.ofSeconds(10))
        ));

        FulfillmentReport report = new ScenarioVerifier().verify(supplier, scenario, List.of(
            new Event("ADT^A01|one", now.minusSeconds(3))
        ), clock);

        assertFalse(report.fulfilled());
        assertTrue(report.results().get(0).fulfilled());
        assertFalse(report.results().get(1).fulfilled());
    }

    @Test public void parsesStructuredKeyValueEvents() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        ParsedEvent event = new DefaultEventParser().parse(
            "type=payment supplier=acme invoice=INV-7 amount=42",
            now
        );

        assertEquals(event.field("type").orElseThrow(), "payment");
        assertEquals(event.field("supplier").orElseThrow(), "acme");
        assertEquals(event.field("invoice").orElseThrow(), "INV-7");
    }

    @Test public void parsesFlatJsonEvents() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        ParsedEvent event = new DefaultEventParser().parse(
            "{\"event\":\"shipment\",\"supplier\":\"acme\",\"po\":\"PO-99\"}",
            now
        );

        assertEquals(event.field("event").orElseThrow(), "shipment");
        assertEquals(event.field("supplier").orElseThrow(), "acme");
        assertEquals(event.field("po").orElseThrow(), "PO-99");
    }

    @Test 
    public void streamingVerifierEmitsTemplateTokensAsConditionsAreFulfilled() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        Clock clock = Clock.fixed(now, ZoneOffset.UTC);
        Supplier supplier = new Supplier("Acme", List.of());
        SupplierScenario scenario = new SupplierScenario("Invoice approval", List.of(
            new Condition("Invoice received", "event", "invoice", Duration.ofMinutes(10), Duration.ofSeconds(10), "invoice:{{invoice}}"),
            new Condition("Payment received", "event", "payment", Duration.ofMinutes(10), Duration.ofSeconds(10), "paid:{{invoice}}")
        ));
        StreamingScenarioVerifier verifier = new StreamingScenarioVerifier(supplier, scenario, clock);
        DefaultEventParser parser = new DefaultEventParser();

        Optional<FulfillmentToken> first = verifier.accept(parser.parse(
            "event=invoice supplier=acme invoice=INV-7",
            now
        ));
        Optional<FulfillmentToken> ignored = verifier.accept(parser.parse(
            "event=note supplier=acme invoice=INV-7",
            now.plusSeconds(1)
        ));
        Optional<FulfillmentToken> second = verifier.accept(parser.parse(
            "event=payment supplier=acme invoice=INV-7",
            now.plusSeconds(2)
        ));

        assertTrue(first.isPresent());
        assertEquals(first.get().token(), "invoice:INV-7");
        assertTrue(ignored.isEmpty());
        assertTrue(second.isPresent());
        assertEquals(second.get().token(), "paid:INV-7");
        assertTrue(verifier.complete());
    }

    @Test public void conditionCanMatchHierarchicalFieldsAndOperators() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        ParsedEvent event = new DefaultEventParser().parse(
            "msh.messageType=ADT^A01 msh.messageControlId=ACME-42 pid.patientId=P123",
            now
        );
        Condition condition = new Condition("Admission", List.of(
            FieldAssertion.equalsTo("msh.messageType", "ADT^A01"),
            FieldAssertion.matches("msh.messageControlId", "^ACME-[0-9]+$"),
            FieldAssertion.exists("pid.patientId")
        ), Duration.ofMinutes(5), Duration.ofSeconds(10), "admission:{{pid.patientId}}:{{msh.messageControlId}}");

        assertTrue(condition.matches(event, now));
        assertEquals(condition.renderToken(event), "admission:P123:ACME-42");
    }

    @Test public void loadsSupplierTemplateFromYaml() throws Exception {
        Path template = Files.createTempFile("receiverman-template", ".yml");
        Files.writeString(template, """
            supplier: Acme HL7
            routeBy: pid.patientId
            scenarios:
              - name: Admission result flow
                expect:
                  - name: Admission received
                    within: 10s
                    maxAge: 5m
                    emit: "admission:{{pid.patientId}}:{{msh.messageControlId}}"
                    match:
                      - field: msh.messageType
                        equals: ADT^A01
                      - field: msh.messageControlId
                        matches: "^ACME-[0-9]+$"
                      - field: pid.patientId
                        exists: true
            """);

        SupplierTemplate loaded = new SupplierTemplateLoader().load(template);
        SupplierScenario scenario = loaded.supplier().scenarios().getFirst();
        Condition condition = scenario.conditions().getFirst();

        assertEquals(loaded.supplier().name(), "Acme HL7");
        assertEquals(loaded.routeBy(), "pid.patientId");
        assertEquals(scenario.name(), "Admission result flow");
        assertEquals(condition.assertions().size(), 3);
        assertEquals(condition.renderToken(new DefaultEventParser().parse(
            "msh.messageType=ADT^A01 msh.messageControlId=ACME-42 pid.patientId=P123",
            Instant.parse("2026-05-24T12:00:00Z")
        )), "admission:P123:ACME-42");
    }

    @Test public void routerKeepsInterleavedScenarioInstancesSeparate() {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        Clock clock = Clock.fixed(now, ZoneOffset.UTC);
        Supplier supplier = new Supplier("Demo Supplier", List.of());
        SupplierScenario scenario = new SupplierScenario("Admission result flow", List.of(
            new Condition("Admission received", "msh.messageType", "ADT^A01", Duration.ofMinutes(10), Duration.ofSeconds(10), "admission:{{pid.patientId}}"),
            new Condition("Result received", "msh.messageType", "ORU^R01", Duration.ofMinutes(10), Duration.ofSeconds(10), "result:{{pid.patientId}}")
        ));
        ScenarioRouter router = new ScenarioRouter(supplier, scenario, "patientId", clock);
        DefaultEventParser parser = new DefaultEventParser();

        Optional<RoutedFulfillment> p1Admission = router.route(parser.parse("type=ADT^A01 patientId=P1", now));
        Optional<RoutedFulfillment> p2Admission = router.route(parser.parse("type=ADT^A01 patientId=P2", now.plusSeconds(1)));
        Optional<RoutedFulfillment> p1Result = router.route(parser.parse("type=ORU^R01 patientId=P1", now.plusSeconds(2)));
        Optional<RoutedFulfillment> p2Result = router.route(parser.parse("type=ORU^R01 patientId=P2", now.plusSeconds(3)));

        assertEquals(router.activeRouteCount(), 2);
        assertEquals(p1Admission.orElseThrow().routeKey(), "P1");
        assertEquals(p2Admission.orElseThrow().routeKey(), "P2");
        assertEquals(p1Result.orElseThrow().fulfillmentToken().token(), "result:P1");
        assertEquals(p2Result.orElseThrow().fulfillmentToken().token(), "result:P2");
        assertTrue(router.verifier("P1").orElseThrow().complete());
        assertTrue(router.verifier("P2").orElseThrow().complete());
    }

    @Test public void routerAcceptsIndependentRoutesConcurrently() throws Exception {
        Instant now = Instant.parse("2026-05-24T12:00:00Z");
        Clock clock = Clock.fixed(now, ZoneOffset.UTC);
        Supplier supplier = new Supplier("Demo Supplier", List.of());
        SupplierScenario scenario = new SupplierScenario("Single event", List.of(
            new Condition("Result received", "msh.messageType", "ORU^R01", Duration.ofMinutes(10), Duration.ofSeconds(10), "result:{{pid.patientId}}")
        ));
        ScenarioRouter router = new ScenarioRouter(supplier, scenario, "patientId", clock);
        DefaultEventParser parser = new DefaultEventParser();
        ExecutorService pool = Executors.newFixedThreadPool(4);
        List<Callable<Optional<RoutedFulfillment>>> tasks = new ArrayList<>();

        for (int i = 0; i < 20; i++) {
            String patientId = "P" + i;
            tasks.add(() -> router.route(parser.parse("type=ORU^R01 patientId=" + patientId, now)));
        }

        List<Future<Optional<RoutedFulfillment>>> futures = pool.invokeAll(tasks);
        pool.shutdown();

        for (Future<Optional<RoutedFulfillment>> future : futures) {
            assertTrue(future.get().isPresent());
        }
        assertEquals(router.activeRouteCount(), 20);
    }
}
